
USER_PAPEL_DISTRIBUIDORA = 1
USER_PAPEL_CLIENTE = 2

CHOICES_USER_PAPEL = (
    (USER_PAPEL_DISTRIBUIDORA, 'Distribuidora'),
    (USER_PAPEL_CLIENTE, 'Cliente'),
)

METODO_REGISTRO_EMAIL = 1
METODO_REGISTRO_GOOGLE = 2

CHOICES_METODO_REGISTRO = [
    (METODO_REGISTRO_EMAIL, 'Email'),
    (METODO_REGISTRO_GOOGLE, 'Google'),
]

